[package]
name = "aws-lc-ring-facade"
version = "0.1.0"
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
alloc = []
default = ["alloc"]
asan = ["aws-lc-sys/asan"]

[dependencies]
untrusted = { version = "0.7.1" }
aws-lc-sys = { path = "deps/aws-lc-sys", version = "0.1.0" }
zeroize = "1.5"
libc = "0.2"

[dev-dependencies]
rand = "0.8"
paste = "1.0"
criterion = "0.4"
ring = "0.16"
regex = "1.6.0"
lazy_static = "1.4.0"

[[bench]]
name = "aead_benchmark"
harness = false

[[bench]]
name = "digest_benchmark"
harness = false

[[bench]]
name = "hkdf_benchmark"
harness = false

[[bench]]
name = "hmac_benchmark"
harness = false

[[bench]]
name = "pbkdf2_benchmark"
harness = false

[[bench]]
name = "quic_benchmark"
harness = false

[[bench]]
name = "rsa_benchmark"
harness = false

[[bench]]
name = "ecdsa_benchmark"
harness = false

[[bench]]
name = "ed25519_benchmark"
harness = false

[[bench]]
name = "agreement_benchmark"
harness = false
