[package]
name = "aws-lc-ring-facade"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
untrusted = { version = "0.9" }
aws-lc-sys = { path = "deps/aws-lc-sys", version = "0.1.0" }
zeroize = "1.5"
hex = "0.4"
libc = "0.2"

[dev-dependencies]
rand = "0.8"
paste = "1.0"
criterion = "0.3"
ring = "0.16"

[[bench]]
name = "aead_benchmark"
harness = false

[[bench]]
name = "digest_benchmark"
harness = false

[[bench]]
name = "quic_benchmark"
harness = false

