[package]
name = "aws-lc-ring-facade"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
untrusted = { version = "0.9" }
aws-lc-sys = { path = "deps/aws-lc-sys", version = "0.1.0" }
zeroize = "1.5"

[dev-dependencies]
ring = "0.16"
rand = "0.8"
libc = "0.2"